# Generated by Django 5.2 on 2025-06-09 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('seleccion_multiple', 'Selección Múltiple'), ('verdadero_falso', 'Verdadero o Falso')], default='seleccion_multiple', max_length=20)),
                ('nivel', models.CharField(choices=[('facil', 'Fácil'), ('intermedio', 'Intermedio'), ('dificil', 'Difícil')], max_length=15)),
                ('categoria', models.CharField(choices=[('rcp', 'RCP'), ('convulsiones', 'Convulsiones'), ('fracturas', 'Fracturas'), ('quemaduras', 'Quemaduras'), ('shock', 'Shock anafiláctico'), ('hemorragias', 'Hemorragias'), ('desmayos', 'Desmayos'), ('atragantamiento', 'Atragantamiento')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('valor', models.IntegerField(default=0)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='quiz.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('opcion_seleccionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.opcionrespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.pregunta')),
            ],
        ),
    ]
