# Generated by Django 5.2 on 2025-06-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionrespuesta',
            name='es_correcta',
            field=models.BooleanField(default=False),
        ),
    ]
