# Generated by Django 5.2.2 on 2025-06-18 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAnimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emocion', models.CharField(choices=[('feliz', 'Feliz'), ('calma', 'Calma'), ('neutral', 'Neutral'), ('triste', 'Triste'), ('ansioso', 'Ansioso'), ('enojado', 'Enojado')], max_length=20)),
                ('nota', models.TextField(blank=True)),
                ('momento', models.CharField(choices=[('manana', 'Manana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'fecha'], name='emociones_e_usuario_684633_idx')],
                'unique_together': {('usuario', 'fecha', 'momento')},
            },
        ),
    ]
