# Generated by Django 5.2.2 on 2025-06-11 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaEmocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emocion', models.CharField(choices=[('feliz', 'Feliz'), ('triste', 'Triste'), ('estresado', 'Estresado'), ('motivado', 'Motivado'), ('cansado', 'Cansado'), ('agradecido', 'Agradecido')], max_length=20)),
                ('nota', models.TextField(blank=True)),
                ('gratitud', models.TextField(blank=True)),
                ('momento', models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
